global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
  - /etc/prometheus/alerts.yml
scrape_configs:
  - job_name: shop-admin
    metrics_path: /actuator/prometheus
    basic_auth:
      username: metrics
      password_file: /tmp/metrics-password
    static_configs:
      - targets: ['backend:8080']
