import {useCallback,useEffect,useState} from 'react';
import {Alert,App as AntApp,Button,Card,Form,Input,InputNumber,Layout,Menu,Modal,Popconfirm,Select,Space,Spin,Statistic,Switch,Table,Tag} from 'antd';
import {DashboardOutlined,TeamOutlined,SafetyOutlined,ApartmentOutlined,AppstoreOutlined,BookOutlined,AuditOutlined,LogoutOutlined,PlusOutlined,ReloadOutlined,LockOutlined} from '@ant-design/icons';
import {PageContainer} from '@ant-design/pro-components';
import {client,unwrap,setToken,hasToken} from './api/client';
import type {components} from './api/schema';
import {loginBody,passwordBody,userBody,roleBody,departmentBody,permissionBody,dictionaryBody} from './api/forms';
import type {LoginValues,PasswordValues,RecordValues} from './api/forms';
type S=components['schemas'];type Me=S['Me'];type User=S['User'];type Role=S['Role'];type Dept=S['Dept'];type Perm=S['Permission'];type Dict=S['Dict'];
type Kind='users'|'roles'|'departments'|'permissions'|'dictionaries'|'audit-logs'|'overview';
type Row=User&Role&Dept&Perm&Dict;
const labels:Record<Kind,string>={overview:'工作台',users:'用户管理',roles:'角色管理',departments:'组织架构',permissions:'菜单权限',dictionaries:'数据字典','audit-logs':'操作审计'};
const icons={overview:<DashboardOutlined/>,users:<TeamOutlined/>,roles:<SafetyOutlined/>,departments:<ApartmentOutlined/>,permissions:<AppstoreOutlined/>,dictionaries:<BookOutlined/>,'audit-logs':<AuditOutlined/>};
export default function Root(){return <AntApp><Admin/></AntApp>}
function Admin(){const {message}=AntApp.useApp();const [me,setMe]=useState<Me>();const [initial,setInitial]=useState(hasToken());const [kind,setKind]=useState<Kind>('overview');const [menu,setMenu]=useState<Perm[]>([]);const [passwordOpen,setPasswordOpen]=useState(false);const [passwordForm]=Form.useForm<PasswordValues>();
 const loadMe=useCallback(async()=>{try{const [m,r]=await Promise.all([client.GET('/api/auth/me'),client.GET('/api/menus')]);setMe(unwrap(m));setMenu(unwrap(r));}catch(e){setToken('');setMe(undefined);message.error((e as Error).message);}finally{setInitial(false);}},[message]);
 useEffect(()=>{if(hasToken())void loadMe();const expired=()=>setMe(undefined);window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired)},[loadMe]);
 const logout=async()=>{try{unwrap(await client.POST('/api/auth/logout'));}finally{setToken('');setMe(undefined);setKind('overview')}};
 if(initial)return <div className="loading"><Spin size="large"/></div>;
 if(!me)return <Login onLogin={loadMe}/>;
 const allowed=(code:string)=>!!me.permissions?.includes('*')||!!me.permissions?.includes(code);
 const keys=new Set(menu.map(m=>m.path?.slice(1)));const items=(Object.keys(labels) as Kind[]).filter(k=>k==='overview'||keys.has(k)).map(k=>({key:k,label:labels[k],icon:icons[k]}));
 return <Layout className="shell"><Layout.Sider width={232} breakpoint="lg" collapsedWidth={64}><div className="brand"><span className="brandmark">澄</span><div>澄明 <small>WORKSPACE</small></div></div><div className="nav-label">企业管理平台</div><Menu theme="dark" mode="inline" selectedKeys={[kind]} items={items} onClick={e=>setKind(e.key as Kind)}/><div className="side-foot"><span className="live-dot"/> 系统工作空间 <small>版本 1.0.0</small></div></Layout.Sider><Layout><Layout.Header className="topbar"><span>组织与权限中心 <span className="slash">/</span> {labels[kind]}</span><Space><span className="avatar">{me.username?.[0]?.toUpperCase()}</span><strong>{me.username}</strong><Button type="text" icon={<LockOutlined/>} onClick={()=>setPasswordOpen(true)}>修改密码</Button><Button type="text" icon={<LogoutOutlined/>} onClick={()=>void logout()}>退出</Button></Space></Layout.Header><Layout.Content><PageContainer title={labels[kind]} subTitle={kind==='overview'?'把组织、权限与日常运营，放在同一个工作空间。':'清晰管理每一条记录，让协作有序发生。'} breadcrumb={{items:[{title:'工作空间'},{title:labels[kind]}]}}>{kind==='overview'?<Overview me={me}/>:<Records key={kind} kind={kind} allowed={allowed}/>}</PageContainer><footer>澄明管理平台 · 让每一次操作都有迹可循</footer></Layout.Content></Layout>
 <Modal title="修改个人密码" open={passwordOpen} onCancel={()=>setPasswordOpen(false)} onOk={async()=>{try{const body=passwordBody(await passwordForm.validateFields());unwrap(await client.POST('/api/account/password',{body}));message.success('密码已修改，请重新登录');setToken('');setMe(undefined);setPasswordOpen(false);passwordForm.resetFields();}catch(e){if(e instanceof Error)message.error(e.message);}}}><Form<PasswordValues> form={passwordForm} layout="vertical"><Form.Item name="oldPassword" label="原密码" rules={[{required:true}]}><Input.Password/></Form.Item><Form.Item name="newPassword" label="新密码" rules={[{required:true,min:12,max:72}]}><Input.Password/></Form.Item></Form></Modal></Layout>
}
function Login({onLogin}:{onLogin:()=>Promise<void>}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');return <div className="login"><div className="login-story"><div className="brand"><span className="brandmark">澄</span>澄明 WORKSPACE</div><div><div className="eyebrow">CLARITY IN EVERY OPERATION</div><h1>管理有序，<br/>协作清晰。</h1><p>连接团队、组织与权限。<br/>从一个可靠的工作空间开始。</p><div className="orbit"><span>组织</span><span>权限</span><span>协作</span></div></div><small>企业管理平台 / 2026</small></div><div className="login-form"><div className="eyebrow">WELCOME BACK</div><h2>登录工作空间</h2><p>使用你的企业账号继续</p>{error?<Alert type="error" showIcon message={error}/>:null}<Form<LoginValues> layout="vertical" onFinish={async(values)=>{setBusy(true);setError('');try{const result=unwrap(await client.POST('/api/auth/login',{body:loginBody(values)}));setToken(result.token!);await onLogin();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Form.Item name="username" label="账号" rules={[{required:true,message:'请输入账号'}]}><Input size="large" autoComplete="username" placeholder="请输入账号"/></Form.Item><Form.Item name="password" label="密码" rules={[{required:true,message:'请输入密码'}]}><Input.Password size="large" autoComplete="current-password" placeholder="请输入密码"/></Form.Item><Button size="large" type="primary" htmlType="submit" loading={busy} block>登录工作空间 →</Button></Form><small>账号由管理员分配 · 权限由组织统一管理</small></div></div>}
function Overview({me}:{me:Me}){const [stats,setStats]=useState<S['Overview']>();const [error,setError]=useState('');useEffect(()=>{let active=true;client.GET('/api/overview').then(r=>{if(active)setStats(unwrap(r));}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);return <><div className="welcome"><div className="eyebrow">YOUR WORKSPACE, CONNECTED</div><h2>你好，{me.username} <span>☀</span></h2><p>从这里了解你的团队，管理组织中的每一个角色。</p><Tag color="cyan">权限范围内的数据</Tag></div>{error?<Alert type="error" message={error}/>:null}<div className="stats">{[['可见用户',stats?.users,<TeamOutlined/>],['可见部门',stats?.departments,<ApartmentOutlined/>],['系统角色',stats?.roles,<SafetyOutlined/>],['操作记录',stats?.operations,<AuditOutlined/>]].map(([label,value,icon])=><Card key={String(label)}><div className="stat-icon">{icon}</div><Statistic title={label} value={value as number|undefined} loading={!stats}/></Card>)}</div><div className="overview-grid"><Card title="工作空间指南"><div className="guide"><b>01</b><div><h3>建立组织结构</h3><p>让部门与团队的关系清晰可见。</p></div></div><div className="guide"><b>02</b><div><h3>按职责分配权限</h3><p>通过角色管理访问能力，通过数据范围保护业务记录。</p></div></div><div className="guide"><b>03</b><div><h3>让操作有据可查</h3><p>审计记录帮助你了解变更与操作结果。</p></div></div></Card><Card title="管理原则"><Tag color="green">后端权限校验</Tag><h3>合适的人，看到合适的数据。</h3><p className="muted">菜单与按钮遵循你的访问权限。敏感操作由服务端再次校验，跨部门数据根据角色范围隔离。</p><div className="principle">清晰 / 克制 / 可追溯</div></Card></div></>}
function Records({kind,allowed}:{kind:Exclude<Kind,'overview'>;allowed:(c:string)=>boolean}){const {message}=AntApp.useApp();const [rows,setRows]=useState<unknown[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [q,setQ]=useState('');const [version,setVersion]=useState(0);const [editing,setEditing]=useState<Row|null>();const [saving,setSaving]=useState(false);const [depts,setDepts]=useState<Dept[]>([]);const [perms,setPerms]=useState<Perm[]>([]);const [roles,setRoles]=useState<Role[]>([]);const [roleUser,setRoleUser]=useState<User>();const [roleIds,setRoleIds]=useState<number[]>([]);const [form]=Form.useForm<RecordValues>();
 const admin=allowed('*');const writable=kind==='users'?allowed('user:write'):kind==='dictionaries'?allowed('dict:write'):kind==='audit-logs'?false:admin;
 useEffect(()=>{let active=true;setLoading(true);setError('');async function load(){let data:unknown[];let count=0;
 if(kind==='users'){const p=unwrap(await client.GET('/api/users',{params:{query:{q,page,size:20}}}));data=p.items||[];count=p.total||0;}
 else if(kind==='audit-logs'){const p=unwrap(await client.GET('/api/audit-logs',{params:{query:{page,size:20}}}));data=p.items||[];count=p.total||0;}
 else if(kind==='roles')data=unwrap(await client.GET('/api/roles'));
 else if(kind==='departments')data=unwrap(await client.GET('/api/departments'));
 else if(kind==='permissions')data=unwrap(await client.GET('/api/permissions'));
 else data=unwrap(await client.GET('/api/dictionaries'));
 if(active){setRows(data);setTotal(count||data.length);}}
 load().catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[kind,q,page,version]);
 useEffect(()=>{let active=true;Promise.all([client.GET('/api/departments').then(unwrap),admin?client.GET('/api/permissions').then(unwrap):Promise.resolve([]),admin?client.GET('/api/roles').then(unwrap):Promise.resolve([])]).then(([d,p,r])=>{if(active){setDepts(d);setPerms(p);setRoles(r);}}).catch(e=>{if(active)message.error(e.message)});return()=>{active=false}},[admin,version,message]);
 const refresh=()=>setVersion(v=>v+1);
 const open=(row:Row|null)=>{form.resetFields();form.setFieldsValue(row||{enabled:true,sort:0,dataScope:'SELF',type:kind==='permissions'?'MENU':undefined,permissionIds:[]});setEditing(row)};
 const remove=async(id:number)=>{try{const params={path:{id}};if(kind==='users')unwrap(await client.DELETE('/api/users/{id}',{params}));else if(kind==='roles')unwrap(await client.DELETE('/api/roles/{id}',{params}));else if(kind==='departments')unwrap(await client.DELETE('/api/departments/{id}',{params}));else if(kind==='permissions')unwrap(await client.DELETE('/api/permissions/{id}',{params}));else if(kind==='dictionaries')unwrap(await client.DELETE('/api/dictionaries/{id}',{params}));message.success('删除成功');refresh();}catch(e){message.error((e as Error).message)}};
 const save=async()=>{try{const values=await form.validateFields();setSaving(true);const id=editing?.id;const params={path:{id:id!}};
 if(kind==='users'){const body=userBody(values);if(id)unwrap(await client.PUT('/api/users/{id}',{params,body}));else unwrap(await client.POST('/api/users',{body}));}
 else if(kind==='roles'){const body=roleBody(values);if(id)unwrap(await client.PUT('/api/roles/{id}',{params,body}));else unwrap(await client.POST('/api/roles',{body}));}
 else if(kind==='departments'){const body=departmentBody(values);if(id)unwrap(await client.PUT('/api/departments/{id}',{params,body}));else unwrap(await client.POST('/api/departments',{body}));}
 else if(kind==='permissions'){const body=permissionBody(values);if(id)unwrap(await client.PUT('/api/permissions/{id}',{params,body}));else unwrap(await client.POST('/api/permissions',{body}));}
 else if(kind==='dictionaries'){const body=dictionaryBody(values);if(id)unwrap(await client.PUT('/api/dictionaries/{id}',{params,body}));else unwrap(await client.POST('/api/dictionaries',{body}));}
 message.success('保存成功');setEditing(undefined);refresh();}catch(e){if(e instanceof Error)message.error(e.message)}finally{setSaving(false)}};
 const status={title:'状态',dataIndex:'enabled',render:(v:boolean)=><Tag color={v?'green':'default'}>{v?'启用':'停用'}</Tag>};
 const columns:Record<string,unknown>[] = kind==='users'?[{title:'用户',dataIndex:'displayName',render:(v:string,r:User)=><Space><span className="table-avatar">{v?.[0]}</span><div><strong>{v}</strong><div className="muted">{r.username}</div></div></Space>},{title:'部门',dataIndex:'deptName'},status]:kind==='roles'?[{title:'角色名称',dataIndex:'name'},{title:'编码',dataIndex:'code'},{title:'数据范围',dataIndex:'dataScope',render:(v:string)=>({ALL:'全部',DEPT_TREE:'本部门及下级',DEPT:'本部门',SELF:'本人'}[v])},status]:kind==='departments'?[{title:'部门名称',dataIndex:'name'},{title:'上级部门',dataIndex:'parentId',render:(v:number)=>depts.find(d=>d.id===v)?.name||'—'}]:kind==='permissions'?[{title:'权限名称',dataIndex:'name'},{title:'权限编码',dataIndex:'code'},{title:'类型',dataIndex:'type',render:(v:string)=><Tag>{v}</Tag>},{title:'路径',dataIndex:'path'}]:kind==='dictionaries'?[{title:'字典类型',dataIndex:'type'},{title:'显示文本',dataIndex:'label'},{title:'值',dataIndex:'value'},{title:'排序',dataIndex:'sort'},status]:[{title:'操作人',dataIndex:'username'},{title:'操作',dataIndex:'action'},{title:'结果',dataIndex:'outcome',render:(v:string)=><Tag color={v==='SUCCESS'?'green':'red'}>{v==='SUCCESS'?'成功':'失败'}</Tag>},{title:'耗时',dataIndex:'durationMs',render:(v:number)=>`${v} ms`},{title:'时间',dataIndex:'createdAt'}];
 if(writable)columns.push({title:'操作',key:'actions',render:(_:unknown,r:Row)=><Space><Button type="link" size="small" onClick={()=>open(r)}>编辑</Button>{kind==='users'&&admin?<Button type="link" size="small" onClick={()=>{setRoleUser(r);setRoleIds(r.roleIds||[])}}>分配角色</Button>:null}<Popconfirm title="确认删除这条记录？" onConfirm={()=>remove(r.id!)}><Button type="link" size="small" danger>删除</Button></Popconfirm></Space>});
 const text=(name:keyof RecordValues,label:string,required=true)=> <Form.Item name={name} label={label} rules={[{required,message:`请输入${label}`}]}><Input maxLength={name==='path'?128:64} disabled={!!editing&&(name==='username'||name==='code')}/></Form.Item>;
 return <><Card className="records"><div className="table-toolbar"><div><strong>{labels[kind]}</strong><span className="count">{total} 条记录</span></div><Space>{kind==='users'?<Input.Search placeholder="搜索用户名或姓名" allowClear onSearch={v=>{setQ(v);setPage(1)}} style={{width:240}}/>:null}<Button icon={<ReloadOutlined/>} onClick={refresh} aria-label="刷新"/>{writable?<Button type="primary" icon={<PlusOutlined/>} onClick={()=>open(null)}>新增</Button>:null}</Space></div>{error?<Alert type="error" showIcon message={error}/>:null}<Table rowKey="id" dataSource={rows as Row[]} columns={columns} loading={loading} scroll={{x:700}} pagination={{current:page,pageSize:20,total,onChange:setPage,showSizeChanger:false,showTotal:t=>`共 ${t} 条`}}/></Card>
 <Modal title={`${editing?'编辑':'新增'}${labels[kind]}`} open={editing!==undefined} onCancel={()=>setEditing(undefined)} onOk={()=>void save()} confirmLoading={saving} destroyOnClose><Form<RecordValues> form={form} layout="vertical">
 {kind==='users'?<>{text('username','用户名')}{text('displayName','姓名')}<Form.Item name="deptId" label="所属部门" rules={[{required:true}]}><Select options={depts.map(d=>({value:d.id,label:d.name}))}/></Form.Item><Form.Item name="password" label={editing?'重置密码（留空不修改）':'初始密码'} rules={[{required:!editing,min:12,max:72}]}><Input.Password/></Form.Item></>:null}
 {kind==='roles'?<>{text('code','角色编码')}{text('name','角色名称')}<Form.Item name="dataScope" label="数据范围" rules={[{required:true}]}><Select options={[{value:'SELF',label:'本人'},{value:'DEPT',label:'本部门'},{value:'DEPT_TREE',label:'本部门及下级'},{value:'ALL',label:'全部'}]}/></Form.Item><Form.Item name="permissionIds" label="权限"><Select mode="multiple" optionFilterProp="label" options={perms.map(p=>({value:p.id,label:`${p.name} · ${p.code}`}))}/></Form.Item></>:null}
 {kind==='departments'?<>{text('name','部门名称')}<Form.Item name="parentId" label="上级部门" rules={[{required:true}]}><Select options={depts.filter(d=>d.id!==editing?.id).map(d=>({value:d.id,label:d.name}))}/></Form.Item></>:null}
 {kind==='permissions'?<>{text('code','权限编码')}{text('name','权限名称')}<Form.Item name="type" label="类型" rules={[{required:true}]}><Select options={['MENU','BUTTON','API'].map(v=>({value:v,label:v}))}/></Form.Item>{text('path','菜单路径',false)}<Form.Item name="parentId" label="所属菜单"><Select allowClear options={perms.filter(p=>p.type==='MENU'&&p.id!==editing?.id).map(p=>({value:p.id,label:p.name}))}/></Form.Item></>:null}
 {kind==='dictionaries'?<>{text('type','字典类型')}{text('label','显示文本')}{text('value','字典值')}<Form.Item name="sort" label="排序"><InputNumber min={0} max={10000}/></Form.Item></>:null}
 {['users','roles','dictionaries'].includes(kind)?<Form.Item name="enabled" label="启用" valuePropName="checked"><Switch/></Form.Item>:null}
 </Form></Modal><Modal title={`为 ${roleUser?.displayName} 分配角色`} open={!!roleUser} onCancel={()=>setRoleUser(undefined)} onOk={async()=>{try{unwrap(await client.PUT('/api/users/{id}/roles',{params:{path:{id:roleUser!.id!}},body:{roleIds}}));message.success('角色已更新');setRoleUser(undefined);refresh();}catch(e){message.error((e as Error).message)}}}><Select mode="multiple" style={{width:'100%'}} value={roleIds} onChange={setRoleIds} options={roles.filter(r=>r.id!==1).map(r=>({value:r.id,label:r.name}))}/></Modal></>
}
